Feature/BDN-339: Direct integrated GoogleBidding adapter
bidon-io/bidon-sdk-android pull request #119
Opened 2023-08-16 11:02 UTC by AntonZarytski

https://appodeal.atlassian.net/browse/BDN-339

2023-08-16 11:39 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobBannerImpl.kt
> +                payload = requireNotNull(json?.getString("payload")) {
@AntonZarytski payload should be null, because you broke usual admob adapter logic.
see Bidmachine

2023-08-16 11:42 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +        return runBlocking {
runBlocking is really bad, try to change this logic, I think @klukwist can help

2023-08-16 12:09 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +        return runBlocking {
[https://github.com/appodeal/AppodealSDK/blob/3cbccb2951bec0457acedceda62cd8d2f3e33[…]artboost/mediation/googlebiddingadapter/GoogleBiddingAdapter.kt](https://github.com/appodeal/AppodealSDK/blob/3cbccb2951bec0457acedceda62cd8d2f3e33888/sdk/modules/adapters/chartboost/src/main/java/com/chartboost/mediation/googlebiddingadapter/GoogleBiddingAdapter.kt#L219)

2023-08-16 12:10 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobBannerImpl.kt
> +                payload = requireNotNull(json?.getString("payload")) {
[Bidmachine](https://github.com/bidon-io/bidon-sdk-android/blob/3443dbed940c882f85aa2dad6490a5ab526b17db/adapter/bidmachine/src/main/java/org/bidon/bidmachine/impl/BMInterstitialAdImpl.kt#L50)

2023-08-16 13:02 UTC, klukwist requested changes

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/ext/Ext.kt
> +internal fun AdFormat?.isValid() = this == NATIVE || this == null
What does NATIVE mean?

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobBannerImpl.kt
> +                )
Looks a bit better than Pair. imo
```
BidonError.BannerAdNotReady to "Banner param is null"
```

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobBannerImpl.kt
> +        if (!adUnitId.isNullOrBlank() && adParams != null) {
```
        val adUnitId = param?.lineItem?.adUnitId
        val adParams = param
        if (!adUnitId.isNullOrBlank() && adParams != null) {
```

is equal to: 
```
        val adParams = param
        val adUnitId = adParams?.lineItem?.adUnitId
        if (!adUnitId.isNullOrBlank()) {
```

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +    private val adRequestBuilder: AdRequest.Builder by lazy { AdRequest.Builder() }
I'm not sure we need to hold `adRequestBuilder` while `AdmobInterstitialImpl` instance exists.

I believe, we can use create builder locally while requesting.

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +    private val adRequestBuilder: AdRequest.Builder by lazy { AdRequest.Builder() }
as it is implemented in Network.fill() method

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +    private var _context: Context? = null
We don't need to store `_Context`. You can pass it into method `fillInterstitial` directly

2023-08-16 13:02 UTC, klukwist commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
>      private val requiredInterstitialAd: InterstitialAd get() = requireNotNull(interstitialAd)
It seems error prone. We can invoke `destroy()` and then we will receive any callback, for instance:
```
           override fun onAdClicked() {
                logInfo(TAG, "onAdClicked: $this")
                emitEvent(AdEvent.Clicked(requiredInterstitialAd.asAd()))
           }
```
Concurrency/Crash/Bzdyshch/etc. :)

2023-08-16 14:11 UTC, AntonZarytski commented on adapter/admob/src/main/java/org/bidon/admob/ext/Ext.kt
> +internal fun AdFormat?.isValid() = this == NATIVE || this == null
native ad doesnt work with google bidding

2023-08-16 14:11 UTC, AntonZarytski commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +    private val adRequestBuilder: AdRequest.Builder by lazy { AdRequest.Builder() }
> I'm not sure we need to hold adRequestBuilder while AdmobInterstitialImpl instance exists.

Neither am I, but according MAX logic, we need to keep AdRequest, since it used for getToken and for fill()

2023-08-17 08:33 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobRewardedImpl.kt
> +        adRequestBuilder.addNetworkExtrasBundle(RtbAdapter::class.java, networkExtras)
see Chartboost IS AppLovin
`AdMobAdapter::class.java`

2023-08-17 08:47 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
>                  lineItem = popLineItem(demandId) ?: error(BidonError.NoAppropriateAdUnitId),
lineItem can be broke

2023-08-17 12:47 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/impl/AdmobInterstitialImpl.kt
> +            suspendCoroutine { continuation ->
IO

2023-08-23 14:14 UTC, merged