Feature/BDN-453 Regulations fix
bidon-io/bidon-sdk-android pull request #151
Opened 2023-10-19 07:07 UTC by klukwist

https://appodeal.atlassian.net/browse/BDN-453

2023-10-19 15:10 UTC, AntonZarytski approved these changes

2023-10-20 08:40 UTC, da2gl commented on adapter/admob/src/main/java/org/bidon/admob/ext/RegulationExt.kt
> +    putBoolean("IABConsent_SubjectToGDPR", this@asBundle.gdprApplies)
https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/3692633b4a5b51f9e5529a75f2c7a4ea9e0a40bd/Google/src/main/java/com/applovin/mediation/adapters/GoogleMediationAdapter.java#L906

@klukwist по admob не могу найти документации. 
как ты сетишь эти данные? откуда взял?)

2023-10-20 12:37 UTC, da2gl requested changes

2023-10-20 12:37 UTC, da2gl commented on adapter/applovin/src/main/java/org/bidon/applovin/ApplovinAdapter.kt
> +            AppLovinPrivacySettings.setDoNotSell(regulation.hasCcpaConsent, context)
!regulation.hasCcpaConsent should be inverted. 
https://dash.applovin.com/documentation/mediation/android/getting-started/privacy#multi-state-consumer-privacy-laws

2023-10-20 12:37 UTC, da2gl commented on adapter/bigoads/src/main/java/org/bidon/bigoads/BigoAdsAdapter.kt
> +            if (!regulation.usPrivacyString.isNullOrBlank()) {
`if (regulation.ccpaApplies)` ?

2023-10-20 12:37 UTC, da2gl commented on adapter/dtexchange/src/main/java/org/bidon/dtexchange/DTExchangeAdapter.kt
> +            InneractiveAdManager.setGdprConsent(true)
`InneractiveAdManager.setGdprConsent(regulation.hasGdprConsent)` ?

2023-10-20 12:37 UTC, da2gl commented on adapter/dtexchange/src/main/java/org/bidon/dtexchange/DTExchangeAdapter.kt
> +            InneractiveAdManager.setGdprConsent(true)
review`InneractiveAdManager.clearGdprConsentData()` / `InneractiveAdManager.clearUSPrivacyString()` / `InneractiveAdManager.currentAudienceAppliesToCoppa()` logic

2023-10-20 12:37 UTC, da2gl commented on adapter/dtexchange/src/main/java/org/bidon/dtexchange/DTExchangeAdapter.kt
> +        if (!regulation.usPrivacyString.isNullOrBlank()) {
`if (regulation.ccpaApplies)` ?

2023-10-20 12:37 UTC, da2gl commented on adapter/inmobi/src/main/java/org/bidon/inmobi/InmobiAdapter.kt
> +            regulation.iab.tcfV2?.let {
`regulation.gdprConsentString` ?
may be now we don't need to obtain iab object?

2023-10-20 12:37 UTC, da2gl commented on adapter/meta/src/main/java/org/bidon/meta/MetaAudienceAdapter.kt
> +        }
https://developers.facebook.com/docs/audience-network/optimization/best-practices/data-processing-options/

2023-10-20 12:37 UTC, da2gl commented on adapter/mobilefuse/src/main/java/org/bidon/mobilefuse/ext/GetMobileFuseTokenUseCase.kt
> +                .setSubjectToGdpr(regulation.gdprApplies)
may be set like  in adapter/mobilefuse/src/main/java/org/bidon/mobilefuse/MobileFuseAdapter.kt?

2023-10-20 12:37 UTC, da2gl commented on adapter/vungle/src/main/java/org/bidon/vungle/VungleAdapter.kt
> +            Vungle.updateUserCoppaStatus(regulation.coppaApplies)
just true like another adapter
`Vungle.updateUserCoppaStatus(true)`

2023-10-20 12:55 UTC, klukwist commented on adapter/dtexchange/src/main/java/org/bidon/dtexchange/DTExchangeAdapter.kt
> +            InneractiveAdManager.setGdprConsent(true)
Added clearing

2023-10-20 12:56 UTC, klukwist commented on adapter/inmobi/src/main/java/org/bidon/inmobi/InmobiAdapter.kt
> +            regulation.iab.tcfV2?.let {
removed

2023-10-20 13:10 UTC, klukwist commented on adapter/mobilefuse/src/main/java/org/bidon/mobilefuse/ext/GetMobileFuseTokenUseCase.kt
> +                .setSubjectToGdpr(regulation.gdprApplies)
refactored to 
`fun Regulation.toMobileFusePrivacyPreferences(): MobileFusePrivacyPreferences`

2023-10-20 13:24 UTC, da2gl commented on adapter/inmobi/src/main/java/org/bidon/inmobi/InmobiAdapter.kt
> +            regulation.iab.tcfV2?.let {
@klukwist I mean 
```
if (!regulation.gdprConsentString.isNullOrEmpty()) {
    this.put(InMobiSdk.IM_GDPR_CONSENT_IAB, regulation.gdprConsentString)
}
```
instead 
`regulation.iab.tcfV2`

2023-10-20 13:28 UTC, da2gl commented on adapter/meta/src/main/java/org/bidon/meta/MetaAudienceAdapter.kt
> +        }
@klukwist 
by docs it should have empty array 
just make it like [Bidmachine Adapter](https://github.com/bidmachine/BidMachine-Android-SDK/blob/cf4febf4e14aa338a18f4f8a485f92a406d5b7f6/adapters/meta_audience/src/main/java/io/bidmachine/ads/networks/meta_audience/MetaAudienceAdapter.java#L125)

2023-10-20 13:38 UTC, klukwist commented on adapter/inmobi/src/main/java/org/bidon/inmobi/InmobiAdapter.kt
> +            regulation.iab.tcfV2?.let {
I'm not sure we should put publisher value for this `IM_GDPR_CONSENT_IAB`, shouldn't?

2023-10-20 13:44 UTC, klukwist commented on adapter/inmobi/src/main/java/org/bidon/inmobi/InmobiAdapter.kt
> +            regulation.iab.tcfV2?.let {
Added

2023-10-20 13:55 UTC, da2gl commented on adapter/inmobi/src/main/java/org/bidon/inmobi/InmobiAdapter.kt
> +            regulation.iab.tcfV2?.let {
if anything happens, put the blame on me

2023-10-20 14:32 UTC, da2gl approved these changes

2023-10-20 14:43 UTC, merged