Feature/BDN-511: Update Vungle SDK to 7.0.0
bidon-io/bidon-sdk-android pull request #163
Opened 2023-11-24 10:15 UTC by AntonZarytski

https://appodeal.atlassian.net/browse/BDN-511

2023-11-24 15:28 UTC, klukwist requested changes

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/VungleAdapter.kt
> +        VunglePrivacySettings.setCOPPAStatus(regulation.coppaApplies)
Please set COPPA only if it applies 
`if (regulation.coppaApplies) {....`

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/VungleBannerAuctionParams.kt
>  data class VungleFullscreenAuctionParams(
Remove `data` as it has now `val activity: Activity` which does not comply to data class.

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleBannerImpl.kt
> +                logInfo(TAG, "onAdLoad =${baseAd.placementId}. $this")
It seems emitting event should be here
```
emitEvent(AdEvent.Fill(bidonAd))
```

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleBannerImpl.kt
> +        val adListener = object : BaseAdListener {
I suppose it better to move `adListener` into `activity.runOnUiThread`, doesn't it?

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleBannerImpl.kt
> +                emitEvent(AdEvent.Fill(bidonAd))
Wrong place for emitting `AdEvent.Fill`, cause we have just started loading here.

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleInterstitialImpl.kt
> +    private val interstitialListener = object : BaseAdListener {
let's create listener into `override fun load(adParams: VungleFullscreenAuctionParams) {` and don't keep the instance in the class.

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleRewardedImpl.kt
> +    private var rewardedListener = object : RewardedAdListener {
the same as interstitial

2023-11-24 15:28 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleRewardedImpl.kt
>          this.adParams = adParams
please, don't keep the whole `adParams` as a local class variable, cause it has Activity-reference. You need the only placement and payload.

2023-11-24 15:30 UTC, klukwist commented
+ ktlint

2023-11-27 13:39 UTC, AntonZarytski commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleBannerImpl.kt
> +        val adListener = object : BaseAdListener {
I don't think so, I'm not in favour of doing any work at UI. 
As far as I can see, you don't use UI thread further on the stack, so there is no point in creating a listener in UI thread.

2023-11-27 13:58 UTC, AntonZarytski commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleRewardedImpl.kt
>          this.adParams = adParams
I understand correctly that I can remove of adParams in all adType classes?

2023-11-27 15:52 UTC, klukwist commented on adapter/vungle/src/main/java/org/bidon/vungle/impl/VungleRewardedImpl.kt
>          this.adParams = adParams
I don't think so (if you talk about other Adapters). I removed all adParams with context. If you see adParams with Context in other adapter, please, inform me.

2023-11-29 12:10 UTC, klukwist approved these changes

2023-11-29 12:16 UTC, merged