Feature/BDN-616: Updated Applovin SDK to 12.3.1
bidon-io/bidon-sdk-android pull request #179
Opened 2024-03-19 13:33 UTC by AntonZarytski

https://appodeal.atlassian.net/browse/BDN-616

2024-03-19 13:36 UTC, klukwist requested changes

2024-03-19 13:36 UTC, klukwist commented on buildSrc/src/main/kotlin/Versions.kt
> +    private val semantic: String = "1"//""-alpha.2"
This should be reverted. It's for alpha-beta versioning. 
In this case version will be `0.4.291` for the core and `0.4.29.11` for adapters.

2024-03-19 14:42 UTC, klukwist approved these changes

2024-03-20 09:33 UTC, da2gl approved these changes

2024-03-20 09:46 UTC, merged