Feature/BDN-687: Provide auction info to public callback
bidon-io/bidon-sdk-android pull request #210
Opened 2024-07-03 16:39 UTC by AntonZarytski

https://appodeal.atlassian.net/browse/BDN-687

2024-07-09 10:53 UTC, da2gl requested changes

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/refresh/BannersCache.kt
> +    private val cache = sortedMapOf<Pair<Ad, AuctionInfo>, BannerView>({ ad1, ad2 ->
key for map is difficult (pair as key)

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +class BidsInfo(
status should be set also

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +    val noBids: List<BidsInfo>?,
noBids + adUnits can be merge
because on Apd side we need to merge it anyway

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +class BidsInfo(
BidsInfo + AdUnitInfo can have one stucture

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +    val tokenStartTs: Long?,
token info needlessly now

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +                    onFailureCallback?.invoke(null, BidonError.AuctionCancelled)
looks bad
see where call this logic

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +    private var onFailureCallback: ((AuctionInfo?, Throwable) -> Unit)? = null
find better solution 
don't store callback local

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +        noBids = statResult?.noBids ?: listOf(),
here you have auctionData why you store nobids in `statResult` ?

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +        val auctionConfigurationId = auctionData.auctionConfigurationId ?: 0L
for what you store it in val?

2024-07-09 10:53 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +                        val result = conductAuction(
learn destructuring declarations https://kotlinlang.org/docs/destructuring-declarations.html
no any first, second give normal names to variables

2024-07-09 11:01 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/stats/models/StatsAdUnit.kt
> +    val ext: JSONObject?
it send to server?

2024-07-09 11:29 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +    val noBids: List<BidsInfo>?,
No, I cant do this, since it different objects collected during diffirent runtime

2024-07-09 11:29 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +        noBids = statResult?.noBids ?: listOf(),
Because RoundStat is an object that stores data for the whole auction (noBids is auction data). StatRound is used to give data to /stats and to publicCallback(AuctionInfo).

2024-07-09 14:01 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +class BidsInfo(
No, I cant do this, since it different objects collected during diffirent runtime

2024-07-09 14:36 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/stats/models/StatsAdUnit.kt
> +    val ext: JSONObject?
Yes

2024-07-10 11:01 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/models/AuctionResponse.kt
> +            noBids = JsonParsers.parseList(json.optJSONArray("no_bids")) ?: listOf(),
can be parse to `NoBid`object

2024-07-10 11:01 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +    override fun cancel(onFailure: (AuctionInfo?, Throwable) -> Unit) {
check this logic

2024-07-10 11:01 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/stats/models/StatsAdUnit.kt
> +    val ext: JSONObject?
for what?

2024-07-10 11:01 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/ExecuteAuctionUseCase.kt
> +    suspend fun execute(
why you rename?

2024-07-10 11:01 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheImpl.kt
> +    override fun clear(onFailure: (AuctionInfo?, Throwable) -> Unit) {
may be fix cancel for another task

2024-07-10 11:06 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +                            it.toBidsInfo()
can be remove?

2024-07-10 11:10 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/ExecuteAuctionUseCase.kt
> +    suspend fun cancel(resultsCollector: ResultsCollector)
pr

2024-07-10 11:29 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/impl/ExecuteAuctionUseCaseImpl.kt
> +                        resultsCollector.add(getBelowPriceFloorResult(adUnit))
test logic here
duplicate with 
```
adUnitQueue.forEach {
   resultsCollector.add(getBelowPriceFloorResult(it))
}
```

2024-07-10 11:48 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/AuctionInfo.kt
> +internal fun StatsAdUnit.toPublicApi() =
to Ext class

2024-07-10 11:48 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +    private fun getAuctionInfo(
```
private fun getAuctionInfo(auctionData: AuctionResponse, statResult: RoundStat?): AuctionInfo {
    return AuctionInfo(
        auctionId = auctionData.auctionId,
        auctionConfigurationId = auctionData.auctionConfigurationId,
        auctionConfigurationUid = auctionData.auctionConfigurationUid,
        auctionPricefloor = auctionData.pricefloor,
        noBids = statResult?.noBids?.map { it.toPublicApi() },
        adUnits = statResult?.demands?.map { it.toPublicApi() },
    )
}
```

2024-07-10 12:20 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/stats/models/StatsAdUnit.kt
> +    val ext: JSONObject?
errorMessage will send if UnexpectedError or IncorrectAdUnit(BidonError) was occurred during request

2024-07-10 12:20 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/auction/impl/AuctionImpl.kt
> +    override fun cancel(onFailure: (AuctionInfo?, Throwable) -> Unit) {
moved to separate PR

2024-07-10 12:20 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/ExecuteAuctionUseCase.kt
> +    suspend fun execute(
to splitting logic for execute and cancel auction, moved to separate PR

2024-07-10 12:21 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheImpl.kt
> +    override fun clear(onFailure: (AuctionInfo?, Throwable) -> Unit) {
done

2024-07-11 11:17 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheImpl.kt
> +                            resolver.sortWinners(winners).take(settings.cacheCapacity)
it + winners ?
why we miss this logic?

2024-07-11 11:17 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/Auction.kt
> +        onSuccess: (winners: List<AuctionResult>, auctionInfo: AuctionInfo) -> Unit,
there are only winners. all adunits results

2024-07-11 14:19 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/impl/AuctionStatImpl.kt
> +                    status = RoundStatus.Lose.code.takeIf { !isAuctionCanceled }
`roundStatus.code` equals `RoundStatus.Lose` in this case

2024-07-11 14:19 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/impl/AuctionStatImpl.kt
> +                    errorMessage = roundStatus.getStatusMessage(),
why here `demandId = stat.demandId.demandId,` 
AuctionResult.BiddingLose -> `demandId = adUnit.demandId,`

2024-07-11 14:19 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/models/AuctionResponse.kt
> +            noBids = JsonParsers.parseList(json.optJSONArray("no_bids")) ?: listOf(),
nullable?

2024-07-11 15:35 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheImpl.kt
> +                            resolver.sortWinners(winners).take(settings.cacheCapacity)
This logic related to the fact that we used to have multiple rounds, and we would update the winner of the current round by adding the winner from the next round.
Now there is only one round, so nothing can be updated

2024-07-31 12:31 UTC, merged