Feature/BDN-786 Ad Cache core implementation
bidon-io/bidon-sdk-android pull request #239
Opened 2024-11-06 16:08 UTC by da2gl

- [x] Interstitial
- [x] Rewarded Video
- [x] Banners
- [x] Destroy winner ad after show. `destroyAd` method
- [x] Activity Watcher
- [x] Separate Banners ad cachers by banner formats (`Banner`, `LeaderBoard`, `MRec`, `Adaptive`)
- [x] Ad Cache data in `/auction` request
- [x] Check that `placement` stays in ext on `/show` `/click` `/reward` and etc in the same ad instance 
- [x] Ad cache pricefloor stratagy issue (Clearing cache strategy)

This pull request includes several changes to the `Bidon` SDK and the demo app, focusing on implementing ad cache logic, enhancing the `SdkSettings` UI, and improving the `BannerView` class. 

Key changes include:

### Features and Enhancements:
* **Ad Cache Logic:** Implemented ad cache logic for auctions, as documented in the `CHANGELOG.md` file.
* **Ad Cache Settings UI:** Added a new `AdCacheSettingsView` composable function to manage ad cache settings in the demo app. This includes UI components for setting cache size, retry delay, and sort strategy.

### Code Improvements:
* **Refactoring `BannerView`:** Simplified the `BannerView` class by removing unnecessary properties and using the `AdCache` class for caching logic.
* **Method Addition in `BidonSdk`:** Added a `setAdCacheSettings` method to the `BidonSdk` object to allow setting ad cache configurations programmatically.
* **Ad Cache Logic:**: Implemented ad cache logic for auctions in next classes `AdCache`, `AdLoader`, `AdInstance`, `AdCacheSettings`

These changes enhance the functionality and maintainability of the codebase, especially regarding ad caching and UI improvements for managing settings.

2024-11-15 14:58 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/utils/di/DI.kt
> -            factoryWithParams<AdCache> { (demandAd) ->
TODO

2024-11-19 12:53 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
>      private val scope: CoroutineScope by lazy { CoroutineScope(SdkDispatchers.Main) }
this scope  is not canceled anywhere, if user has not set bannerView = null after destroy, scope will work

2024-11-19 17:31 UTC, klukwist requested changes

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
> +        adCache.pop()?.sendLoss(winnerDemandId, winnerEcpm)
Could it be better to comment/remove this logic at all?

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
> +            adCache.clear()
Should we clear the whole cache?

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
>              }
Just not to use 
`val adSource = adCache.peek() as AdSource.Banner<*>?` before `return internalAdSize`
```
       get() {
            return internalAdSize ?: (adCache.peek() as? AdSource.Banner<*>)?.getAdView()?.let { holder ->
                AdSize(widthDp = holder.widthDp, heightDp = holder.heightDp)
                    .also { internalAdSize = it }
            }
        }
```

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
> +            return internalAdSize ?: adSource?.getAdView()?.let { holder ->
should it be synchronized?

```
return internalAdSize ?: synchronized(this) {
    internalAdSize ?:  adSource?.getAdView()?.let { holder ->
        AdSize(widthDp = holder.widthDp, heightDp = holder.heightDp)
            .also { internalAdSize = it }
    }
}
```

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/banner/helper/impl/ActivityProviderImpl.kt
> +        if (activity == currentActivityRef.get()) {
Would it be better to check if an activity is destroyed or in the process of being destroyed? What do you think? This way, we can avoid exposing a problematic activity. :)

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/cache/AdCacheProvider.kt
> +    fun provide(demandAd: DemandAd, bannerFormat: BannerFormat? = null): AdCache
A good pattern is to split interfaces to avoid using unnecessary parameters, such as `BannerFormat` for a fullscreen ad. Sealed interfaces are great for achieving this:
```
internal sealed interface AdCacheProvider {
    interface Fullscreen : AdCacheProvider {
        fun provide(demandAd: DemandAd): AdCache
    }

    interface Banner : AdCacheProvider {
        fun provide(demandAd: DemandAd, bannerFormat: BannerFormat): AdCache
    }
}
```

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/cache/AdCacheProvider.kt
> +    ): AdCache
It might be better to separate Providers by logic as well, ex:
```
internal sealed interface AdCacheProvider {
    interface Fullscreen : AdCacheProvider {
        fun provide(demandAd: DemandAd): AdCache
    }

    interface Banner : AdCacheProvider {
        fun provide(demandAd: DemandAd, bannerFormat: BannerFormat): AdCache
    }
}
```

or

```
internal sealed interface AdCacheProvider {
    fun provide(demandAd: DemandAd): AdCache
    
    interface Fullscreen : AdCacheProvider {
        override fun provide(demandAd: DemandAd): AdCache
    }

    abstract class Banner(val bannerFormat: BannerFormat) : AdCacheProvider {
        abstract override fun provide(demandAd: DemandAd): AdCache
    }
}
```

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheProviderImpl.kt
> +        return adCacheInstances.getOrPut(AdCacheKey(demandAd.adType)) {
> Note that the operation is not guaranteed to be atomic if the map is being modified concurrently.

Could we use smth thread-safe for
`private val adCacheInstances = mutableMapOf<AdCacheKey, AdCache>()`
to prevent concurrency issues, `MutableStateFlow` or `ConcurrentHashMap` or smth else?

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +        results.update { it + adInstance }
Should we check the current `results`-size here?
```
results.update { (it + adInstance).take(cacheSize) }
```

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/interstitial/InterstitialImpl.kt
> +                subscribeToWinner(adSource)
A loaded ad and a displayed ad might differ. Perhaps we shouldn't subscribe to its events, except for onExpired.

This is something worth discussing, probably. What do you think?

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/interstitial/InterstitialImpl.kt
> +                subscribeToWinner(adSource)
But subscribe to it before `showAd()`

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/auction/AdTypeParam.kt
> +    data class Banner(
It should not be a `data class` because `Activity` is not a primitive.

2024-11-19 17:31 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/cache/AdCacheSettingsProvider.kt
> +    sealed class SortStrategy {
`enum class` seems better fit here, doesn't it?

2024-11-20 09:24 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheProviderImpl.kt
> +    private val adCacheInstances = mutableMapOf<AdCacheKey, AdCache>()
AdCacheProvider is singleton, but `adCacheInstances.getOrPut` - the operation is not guaranteed to be atomic if the map is being modified concurrently.
The best way will be using `ConcurrentHashMap<AdCacheKey, AdCache>()` instead

2024-11-20 10:21 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/AdTypeParam.kt
> +    data class Banner(
it's not entirely true that I can't use activity (or another reference type), but I will rewrite this logic to original point of use "data" class.

2024-11-20 10:22 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/cache/AdCacheSettingsProvider.kt
> +    sealed class SortStrategy {
I'll do it

2024-11-20 10:26 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/interstitial/InterstitialImpl.kt
> +                subscribeToWinner(adSource)
I agree it makes sense

2024-11-20 10:30 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
>      private val scope: CoroutineScope by lazy { CoroutineScope(SdkDispatchers.Main) }
good point I don’t have a solution right now, but I’ll think about it

2024-11-20 10:31 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
> +        adCache.pop()?.sendLoss(winnerDemandId, winnerEcpm)
We can leave win/lose methods completely empty
Let's discuss it

2024-11-20 10:32 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
> +            adCache.clear()
see AdCache#clear logic

2024-11-20 10:49 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
> +            return internalAdSize ?: adSource?.getAdView()?.let { holder ->
I don't have an answer why this might be good and why it might be bad for use.
but we can do it

2024-11-20 10:49 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
>              }
okay

2024-11-20 12:16 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/BannerView.kt
>      private val scope: CoroutineScope by lazy { CoroutineScope(SdkDispatchers.Main) }
If a `CoroutineScope` is tied to a view (e.g., directly defined inside a view class or referencing it), and the view instance is garbage collected because there are no references to it, then the scope will also be garbage collected if:

1. There are no ongoing coroutine jobs in the scope.
2. The scope itself doesn't hold any additional strong references.

For full-screen ads, we clear/cancel all `Jobs`, I don’t see any problems with that. 
But it’s difficult for Banner to offer something like that.

2024-11-20 12:58 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheProviderImpl.kt
> +        return adCacheInstances.getOrPut(AdCacheKey(demandAd.adType)) {
I will use MutableStateFlow

2024-11-20 12:58 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheProviderImpl.kt
> +    private val adCacheInstances = mutableMapOf<AdCacheKey, AdCache>()
I will use MutableStateFlow

2024-11-26 13:05 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/helper/impl/ActivityProviderImpl.kt
> +        if (activity == currentActivityRef.get()) {
I also have a non-trivial logic here, where we intercept ad activity from any networks and use it for loader request.
@da2gl fix this

2024-11-28 13:46 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/banner/helper/impl/ActivityProviderImpl.kt
> +        if (activity == currentActivityRef.get()) {
we don't need to check activity in `clearIfCurrent` method because in all cases we will null it out

2024-11-28 13:47 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +        results.update { it + adInstance }
I change this logic, it's can be outdated

2024-11-29 16:54 UTC, klukwist approved these changes

2024-11-29 16:54 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheImpl.kt
> +            val key = adTypeParam.auctionKey ?: DEFAULT_LOADER_KEY
Could it be a good idea to remove `DEFAULT_LOADER_KEY` from `AdCacheImpl`? I believe AdCache should know nothing about "default" `auction_key`.

It seems better to update `AdTypeParam`, smth like:
```
sealed interface AdTypeParam {
    val auctionKey: String
    ...
    class Banner(
        ...
        override val auctionKey: String = "default",
        ...
    ) : AdTypeParam 
}
```
wdyt?

2024-11-29 16:54 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +    private val defaultRetryDelayMs get() = adSettings.retryDelayMs
`defaultRetryDelayMs` – might be renamed to `retryDelayMs`, the cause is it doesn't represent default value, but just a value.
Up to you.

2024-11-29 16:54 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/impl/ExecuteAuctionUseCaseImpl.kt
> +//        adSource.setDemandAd(demandAd)
Do I understand correctly that `setDemandAd` is used for passing extras?
If so, what happens if we set it both here and during the `show` call?

2024-11-29 16:54 UTC, klukwist commented on bidon/src/main/java/org/bidon/sdk/cache/AdCacheSettingsProvider.kt
> +        @IntRange(from = 2_000, to = 64_000) val retryDelayMs: Int
What if use constants?
```
@IntRange(from = MIN_RETRY_DELAY_MS.toLong(), to = MAX_RETRY_DELAY_MS.toLong()) val retryDelayMs: Int
```

Fun fact - `IntRange` accepts Long as a parameters🫣

2024-11-29 16:57 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/auction/usecases/impl/ExecuteAuctionUseCaseImpl.kt
> +//        adSource.setDemandAd(demandAd)
we just rewrite it, we can save it here

2024-12-02 15:33 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +    private val defaultRetryDelayMs get() = adSettings.retryDelayMs
renamed

2024-12-02 15:34 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/cache/AdCacheSettingsProvider.kt
> +        @IntRange(from = 2_000, to = 64_000) val retryDelayMs: Int
just removed annotation, because it looks bad to use inside ad cache logic and to use in api

2024-12-02 15:36 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheImpl.kt
> +            val key = adTypeParam.auctionKey ?: DEFAULT_LOADER_KEY
I can't rewrite/use default auctionKey as "default", because we pass `null` in /auction request and adjacent logic.
I agree with you, I changed this logic but I leave this question is open.

2024-12-02 15:36 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/AdCacheProvider.kt
> +    ): AdCache
an open question

2024-12-03 10:25 UTC, AntonZarytski requested changes

2024-12-03 10:25 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheProviderImpl.kt
> +    }
code duplication, you may use something like:

```
override fun provide(demandAd: DemandAd, bannerFormat: BannerFormat): AdCache {
    val key = when (demandAd.adType) {
        AdType.Banner -> AdCacheKey(demandAd.adType, bannerFormat)
        else -> AdCacheKey(demandAd.adType)
    }
    return getOrCreateCache(key) {
        createAdCache(demandAd, bannerFormat.takeIf { demandAd.adType == AdType.Banner })
    }
}
```

and remove: `provideInterstitialCache`, `provideRewardedCache`, `provideBannerCache`

2024-12-03 14:04 UTC, AntonZarytski approved these changes

2024-12-03 14:06 UTC, da2gl commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdCacheProviderImpl.kt
> +    }
an open question

2024-12-03 14:17 UTC, AntonZarytski approved these changes

2024-12-03 14:17 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +
[optional]
too many conditions 
```
if {
   if {
   //
   } else {
   //
   }
} else {
//
}
```
but I don't have solution how to "straighten" it using `when`

2024-12-03 14:17 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +    }
[optional]
too many conditions 
```
if {
   if {
   //
   } else {
   //
   }
} else {
//
}
```
but I don't have solution how to "straighten" it using `when`

2024-12-03 14:17 UTC, AntonZarytski commented on bidon/src/main/java/org/bidon/sdk/ads/cache/impl/AdLoaderImpl.kt
> +    }
[optional]
too many conditions 
```
if {
   if {
   //
   } else {
   //
   }
} else {
//
}
```
but I don't have solution how to straighten it using `when`

perhaps something like this: 
```
private fun updateAdInstances(newAdInstance: AdInstance) {
        adInstances.update { currentCache ->
            when {
                currentCache.isEmpty() -> { // тут не красиво, но надо
                    currentCache
                }
                currentCache.size < maxCacheSize -> currentCache + newAdInstance
                currentCache.any { it.ecpm < newAdInstance.ecpm } -> {
                    val lowestValueAd = currentCache.minBy { it.ecpm } // что бы избавиться от minByOrNull
                    logInfo(tag, "Replacing ad: ${lowestValueAd.adSource} with ${newAdInstance.adSource}")
                    (currentCache - lowestValueAd + newAdInstance).also {
                        trackExpired(newAdInstance)
                    }
                }
                else -> {
                    logInfo(tag, "New ad discarded due to lower value.")
                    currentCache
                }
            }
        }
    }
```

2024-12-04 16:29 UTC, merged